#!/usr/bin/env python3
"""Generate the checkpoint-parameter loading diagrams used by the docs."""

from __future__ import annotations

import argparse
from html import escape
from pathlib import Path


DOCS_DIR = Path(__file__).resolve().parents[1]
OUTPUT_DIR = DOCS_DIR / "_static" / "checkpoint-loading"

STANDARD_WIDTH = 1000
STANDARD_HEIGHT = 580
LEGEND_WIDTH = STANDARD_WIDTH
LEGEND_HEIGHT = 142

# Shared parameter-slice geometry. The compact legend and every full figure
# deliberately use the same horizontal scale and the same slice primitive.
CELL_SIZE = 36
CELL_GAP = 8
CELL_PITCH = CELL_SIZE + CELL_GAP
CELL_RADIUS = 6
CELL_STROKE_WIDTH = 1.75
ROW_INDEX_GAP = 16
AXIS_TO_INDEX_GAP = 50
AXIS_CENTER_EDGE_INSET = 48
TRACK_TITLE_OFFSET = 50
COLUMN_INDEX_OFFSET = 20

CARD_OUTER_MARGIN = 28
SOURCE_CARD_X = CARD_OUTER_MARGIN
CARD_WIDTH = 390
TARGET_CARD_X = STANDARD_WIDTH - CARD_OUTER_MARGIN - CARD_WIDTH
CARD_Y = 20
CARD_HEIGHT = STANDARD_HEIGHT - 2 * CARD_Y
CARD_CONTENT_INSET = 24
LANE_LABEL_INSET = 28
CARD_TITLE_Y = CARD_Y + 34
HEADER_SEPARATOR_Y = 90
ORGANISM_TITLE_Y = 120
SECTION_SEPARATOR_Y = 300
HEAD_TITLE_Y = 326
DATA_CENTER_BIAS = 22

# Every loading-mode figure uses the same schematic source and target shapes.
EXAMPLE_CHECKPOINT_ORGANISMS = 2
EXAMPLE_CHECKPOINT_TRACKS = 4
EXAMPLE_TARGET_ORGANISMS = 3
EXAMPLE_TARGET_TRACKS = 3

SOURCE_DATA_CENTER_X = SOURCE_CARD_X + CARD_WIDTH / 2 + DATA_CENTER_BIAS
TARGET_DATA_CENTER_X = TARGET_CARD_X + CARD_WIDTH / 2 - DATA_CENTER_BIAS
ORG_SOURCE_X = SOURCE_DATA_CENTER_X - CELL_SIZE / 2
ORG_TARGET_X = TARGET_DATA_CENTER_X - CELL_SIZE / 2
ORG_Y = 154

GRID_Y = 408
HEAD_MAPPING_CENTER_Y = GRID_Y + (
    EXAMPLE_TARGET_ORGANISMS * CELL_SIZE
    + (EXAMPLE_TARGET_ORGANISMS - 1) * CELL_GAP
) / 2

CANVAS_CENTER_X = STANDARD_WIDTH / 2
GATE_LINE_CLEARANCE = 30
CARD_GAP_LEFT = SOURCE_CARD_X + CARD_WIDTH
CARD_GAP_RIGHT = TARGET_CARD_X
CENTRAL_GUTTER = 12
MAPPING_CHIP_X = CARD_GAP_LEFT + CENTRAL_GUTTER
MAPPING_CHIP_WIDTH = CARD_GAP_RIGHT - CARD_GAP_LEFT - 2 * CENTRAL_GUTTER
MAPPING_CHIP_HEIGHT = 30

class Svg:
    """Tiny SVG builder with only the primitives these diagrams need."""

    def __init__(
        self,
        *,
        width: int,
        height: int,
        title: str,
        description: str,
    ) -> None:
        self.width = width
        self.height = height
        self.title = title
        self.description = description
        self.elements: list[str] = []

    def raw(self, value: str) -> None:
        self.elements.append(value)

    def rect(
        self,
        x: float,
        y: float,
        width: float,
        height: float,
        *,
        css_class: str = "",
        radius: float = 0,
        extra: str = "",
    ) -> None:
        class_attr = f' class="{css_class}"' if css_class else ""
        radius_attr = f' rx="{radius}" ry="{radius}"' if radius else ""
        self.raw(
            f'<rect x="{x}" y="{y}" width="{width}" height="{height}"'
            f'{radius_attr}{class_attr}{extra}/>'
        )

    def line(
        self,
        x1: float,
        y1: float,
        x2: float,
        y2: float,
        *,
        css_class: str,
        width: float = 2,
        extra: str = "",
    ) -> None:
        self.raw(
            f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" '
            f'class="{css_class}" stroke-width="{width}"{extra}/>'
        )

    def path(
        self,
        d: str,
        *,
        css_class: str,
        width: float = 3,
        marker: str | None = None,
        extra: str = "",
    ) -> None:
        marker_attr = f' marker-end="url(#{marker})"' if marker else ""
        self.raw(
            f'<path d="{d}" class="{css_class}" fill="none" '
            f'stroke-width="{width}" stroke-linecap="round" '
            f'stroke-linejoin="round"{marker_attr}{extra}/>'
        )

    def circle(
        self,
        cx: float,
        cy: float,
        radius: float,
        *,
        css_class: str,
        extra: str = "",
    ) -> None:
        self.raw(
            f'<circle cx="{cx}" cy="{cy}" r="{radius}" '
            f'class="{css_class}"{extra}/>'
        )

    def text(
        self,
        x: float,
        y: float,
        value: str,
        *,
        css_class: str = "ink",
        anchor: str = "start",
        extra: str = "",
    ) -> None:
        self.raw(
            f'<text x="{x}" y="{y}" class="{css_class}" '
            f'text-anchor="{anchor}" dominant-baseline="middle"{extra}>'
            f'{escape(value)}</text>'
        )

    def render(self) -> str:
        body = "\n  ".join(self.elements)
        return f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by docs/_scripts/generate_checkpoint_loading_diagrams.py. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {self.width} {self.height}"
     role="img" aria-labelledby="svg-title svg-description">
  <title id="svg-title">{escape(self.title)}</title>
  <desc id="svg-description">{escape(self.description)}</desc>
  {DEFS}
  {body}
</svg>
'''


DEFS = '''<defs>
    <style>
      text {
        font-family: Inter, ui-sans-serif, system-ui, -apple-system,
          BlinkMacSystemFont, "Segoe UI", sans-serif;
      }
      .canvas { fill: #f8fafc; }
      .card-shadow { fill: #d8e1eb; opacity: 0.55; }
      .card { fill: #ffffff; stroke: #cbd5e1; }
      .ink { fill: #172033; }
      .muted { fill: #667085; }
      .card-title { fill: #172033; font-size: 17px; font-weight: 750; letter-spacing: 1.8px; }
      .case-title { fill: #172033; font-size: 16px; font-weight: 800; letter-spacing: 1.4px; }
      .lane-label { fill: #667085; font-size: 13px; font-weight: 750; letter-spacing: 1.1px; }
      .index { fill: #172033; font-size: 13px; font-weight: 700; }
      .axis { fill: #667085; font-size: 12px; font-weight: 650; }
      .axis-title { fill: #667085; font-size: 10px; font-weight: 750; letter-spacing: 0.8px; }
      .legend-title { fill: #172033; font-size: 15px; font-weight: 800; letter-spacing: 1px; }
      .legend { fill: #344054; font-size: 13px; font-weight: 700; letter-spacing: 0.35px; }
      .legend-note { fill: #667085; font-size: 12px; font-weight: 650; }
      .cell-text { fill: #344054; font-size: 13px; font-weight: 800; }
      .prefix-label { fill: #356b9a; font-size: 10px; font-weight: 800; letter-spacing: 0.8px; }
      .separator { stroke: #e2e8f0; }
      .neutral-cell { fill: #eef2f6; stroke: #667085; }
      .source-cell { fill: #e7f0fa; stroke: #356b9a; }
      .init-cell { fill: #fbe9e2; stroke: #b65a36; }
      .copied-cell { fill: #e7f0fa; stroke: #b65a36; }
      .unused-cell {
        fill: #f1f5f8;
        stroke: #708da7;
        stroke-dasharray: 5 3;
        stroke-linecap: round;
      }
      .copy-line { stroke: #356b9a; }
      .copy-marker { fill: #356b9a; }
      .mapping-badge { fill: none; stroke: #172033; }
      .badge-text { fill: #172033; font-size: 12px; font-weight: 800; }
      .mapping-chip { fill: #ffffff; stroke: #344054; }
      .mapping-index-text { font-size: 10px; font-weight: 800; }
      .mapping-source-text { fill: #356b9a; }
      .mapping-target-text { fill: #b65a36; }
      .mapping-arrow { fill: #344054; font-size: 12px; font-weight: 800; }
      .stop-ring { fill: #f8fafc; stroke: #b42318; }
      .stop-line { stroke: #b42318; }
      .gate-line { stroke: #98a2b3; }
      @media (prefers-color-scheme: dark) {
        .canvas { fill: #0f172a; }
        .card-shadow { fill: #020617; opacity: 0.7; }
        .card { fill: #172033; stroke: #475569; }
        .ink, .card-title, .case-title, .index, .legend-title { fill: #f8fafc; }
        .muted, .lane-label, .axis, .axis-title, .legend, .legend-note,
        .mapping-arrow, .cell-text { fill: #cbd5e1; }
        .separator { stroke: #334155; }
        .neutral-cell { fill: #334155; stroke: #cbd5e1; }
        .source-cell { fill: #1d3650; stroke: #86b7e2; }
        .init-cell { fill: #492b24; stroke: #f0a083; }
        .copied-cell { fill: #1d3650; stroke: #f0a083; }
        .unused-cell { fill: #263542; stroke: #7895af; }
        .copy-line { stroke: #86b7e2; }
        .copy-marker { fill: #86b7e2; }
        .prefix-label { fill: #86b7e2; }
        .mapping-badge { stroke: #f8fafc; }
        .badge-text { fill: #f8fafc; }
        .mapping-chip { fill: #172033; stroke: #cbd5e1; }
        .mapping-source-text { fill: #86b7e2; }
        .mapping-target-text { fill: #f0a083; }
        .stop-ring { fill: #0f172a; stroke: #f97066; }
        .stop-line { stroke: #f97066; }
        .gate-line { stroke: #94a3b8; }
      }
    </style>
    <marker id="arrow-copy" viewBox="0 0 10 10" refX="8.5" refY="5"
            markerWidth="8" markerHeight="8" orient="auto-start-reverse">
      <path d="M 0 0 L 10 5 L 0 10 z" class="copy-marker"/>
    </marker>
  </defs>'''


STATE_CLASSES = {
    "neutral": "neutral-cell",
    "source": "source-cell",
    "copied": "copied-cell",
    "init": "init-cell",
    "unused": "unused-cell",
}


def grid_width(columns: int) -> float:
    return columns * CELL_SIZE + (columns - 1) * CELL_GAP


def grid_height(rows: int) -> float:
    return rows * CELL_SIZE + (rows - 1) * CELL_GAP


def data_center_x(card_x: float, side: str) -> float:
    """Bias data inward to reserve a mirrored outer annotation rail."""
    direction = 1 if side == "left" else -1
    return card_x + CARD_WIDTH / 2 + direction * DATA_CENTER_BIAS


def centered_grid_x(card_x: float, columns: int, side: str) -> float:
    """Center a parameter grid within its card's data region."""
    return data_center_x(card_x, side) - grid_width(columns) / 2


def annotation_positions(
    *,
    card_x: float,
    group_x: float,
    group_width: float,
    side: str,
) -> tuple[float, float]:
    """Return mirrored index and axis-title centers with safe card margins."""
    if side == "left":
        index_x = group_x - ROW_INDEX_GAP
        axis_x = max(
            index_x - AXIS_TO_INDEX_GAP,
            card_x + AXIS_CENTER_EDGE_INSET,
        )
    else:
        index_x = group_x + group_width + ROW_INDEX_GAP
        axis_x = min(
            index_x + AXIS_TO_INDEX_GAP,
            card_x + CARD_WIDTH - AXIS_CENTER_EDGE_INSET,
        )
    return index_x, axis_x


def add_parameter_slice(svg: Svg, *, x: float, y: float, state: str) -> None:
    """Draw one parameter slice using the shared geometry for every figure."""
    svg.rect(
        x,
        y,
        CELL_SIZE,
        CELL_SIZE,
        css_class=STATE_CLASSES[state],
        radius=CELL_RADIUS,
        extra=f' stroke-width="{CELL_STROKE_WIDTH}"',
    )


def add_badge(svg: Svg, x: float, y: float, label: str) -> None:
    svg.circle(
        x,
        y,
        11,
        css_class="mapping-badge",
        extra=' stroke-width="2"',
    )
    svg.text(x, y + 0.5, label, css_class="badge-text", anchor="middle")


def add_grid(
    svg: Svg,
    *,
    card_x: float,
    x: float,
    y: float,
    rows: int,
    columns: int,
    states: list[list[str]],
    badges: dict[tuple[int, int], str] | None = None,
    side: str,
) -> None:
    badges = badges or {}
    svg.text(
        x + grid_width(columns) / 2,
        y - TRACK_TITLE_OFFSET,
        "TRACK 't' →",
        css_class="axis-title",
        anchor="middle",
    )
    for column in range(columns):
        cx = x + column * CELL_PITCH + CELL_SIZE / 2
        svg.text(cx, y - COLUMN_INDEX_OFFSET, str(column), css_class="axis", anchor="middle")

    row_index_x, row_title_x = annotation_positions(
        card_x=card_x,
        group_x=x,
        group_width=grid_width(columns),
        side=side,
    )
    row_title_y = y + grid_height(rows) / 2
    svg.text(row_title_x, row_title_y - 10, "ORG 'o'", css_class="axis-title", anchor="middle")
    svg.text(row_title_x, row_title_y + 12, "↓", css_class="axis-title", anchor="middle")
    for row in range(rows):
        cy = y + row * CELL_PITCH + CELL_SIZE / 2
        svg.text(row_index_x, cy, str(row), css_class="axis", anchor="middle")
        for column in range(columns):
            cell_x = x + column * CELL_PITCH
            cell_y = y + row * CELL_PITCH
            add_parameter_slice(svg, x=cell_x, y=cell_y, state=states[row][column])
            badge = badges.get((row, column))
            if badge is not None:
                add_badge(
                    svg,
                    cell_x + CELL_SIZE / 2,
                    cell_y + CELL_SIZE / 2,
                    badge,
                )


def add_org_column(
    svg: Svg,
    *,
    card_x: float,
    x: float,
    y: float,
    states: list[str],
    side: str,
    badges: dict[int, str] | None = None,
) -> None:
    badges = badges or {}
    label_x, axis_x = annotation_positions(
        card_x=card_x,
        group_x=x,
        group_width=CELL_SIZE,
        side=side,
    )
    axis_y = y + grid_height(len(states)) / 2
    svg.text(axis_x, axis_y - 10, "ORG 'o'", css_class="axis-title", anchor="middle")
    svg.text(axis_x, axis_y + 12, "↓", css_class="axis-title", anchor="middle")
    for index, state in enumerate(states):
        cell_y = y + index * CELL_PITCH
        add_parameter_slice(svg, x=x, y=cell_y, state=state)
        svg.text(
            label_x,
            cell_y + CELL_SIZE / 2,
            str(index),
            css_class="index",
            anchor="middle",
        )
        badge = badges.get(index)
        if badge is not None:
            add_badge(
                svg,
                x + CELL_SIZE / 2,
                cell_y + CELL_SIZE / 2,
                badge,
            )


def org_center(y: float, index: int) -> float:
    return y + index * CELL_PITCH + CELL_SIZE / 2


def add_gate(
    svg: Svg,
    *,
    y: float,
    left: float = ORG_SOURCE_X + CELL_SIZE + 10,
    right: float = ORG_TARGET_X - 10,
) -> None:
    svg.line(
        left,
        y,
        CANVAS_CENTER_X - GATE_LINE_CLEARANCE,
        y,
        css_class="gate-line",
        width=2.5,
        extra=' stroke-dasharray="6 7"',
    )
    svg.line(
        CANVAS_CENTER_X + GATE_LINE_CLEARANCE,
        y,
        right,
        y,
        css_class="gate-line",
        width=2.5,
        extra=' stroke-dasharray="6 7"',
    )
    svg.circle(CANVAS_CENTER_X, y, 22, css_class="stop-ring", extra=' stroke-width="2.5"')
    svg.line(
        CANVAS_CENTER_X - 10,
        y - 10,
        CANVAS_CENTER_X + 10,
        y + 10,
        css_class="stop-line",
        width=3.5,
        extra=' stroke-linecap="round"',
    )
    svg.line(
        CANVAS_CENTER_X + 10,
        y - 10,
        CANVAS_CENTER_X - 10,
        y + 10,
        css_class="stop-line",
        width=3.5,
        extra=' stroke-linecap="round"',
    )


def add_standard_frame(svg: Svg) -> None:
    svg.rect(0, 0, STANDARD_WIDTH, STANDARD_HEIGHT, css_class="canvas", radius=22)
    for x, title in ((SOURCE_CARD_X, "CHECKPOINT"), (TARGET_CARD_X, "TARGET")):
        svg.rect(
            x + 5,
            CARD_Y + 7,
            CARD_WIDTH,
            CARD_HEIGHT,
            css_class="card-shadow",
            radius=18,
        )
        svg.rect(
            x,
            CARD_Y,
            CARD_WIDTH,
            CARD_HEIGHT,
            css_class="card",
            radius=18,
            extra=' stroke-width="1.5"',
        )
        svg.text(
            x + CARD_WIDTH / 2,
            CARD_TITLE_Y,
            title,
            css_class="card-title",
            anchor="middle",
        )
        svg.line(
            x + CARD_CONTENT_INSET,
            HEADER_SEPARATOR_Y,
            x + CARD_WIDTH - CARD_CONTENT_INSET,
            HEADER_SEPARATOR_Y,
            css_class="separator",
            width=1.5,
        )
        svg.line(
            x + CARD_CONTENT_INSET,
            SECTION_SEPARATOR_Y,
            x + CARD_WIDTH - CARD_CONTENT_INSET,
            SECTION_SEPARATOR_Y,
            css_class="separator",
            width=1.5,
        )
        svg.text(
            x + LANE_LABEL_INSET,
            ORGANISM_TITLE_Y,
            "ORGANISM SLICE 'o'",
            css_class="lane-label",
        )
        svg.text(
            x + LANE_LABEL_INSET,
            HEAD_TITLE_Y,
            "HEAD SLICE (o, t)",
            css_class="lane-label",
        )


def make_legend_diagram() -> str:
    svg = Svg(
        width=LEGEND_WIDTH,
        height=LEGEND_HEIGHT,
        title="Checkpoint loading figure legend",
        description=(
            "Every flat square is one parameter slice, drawn schematically as shape C. "
            "The introductory square is neutral gray to not indicate any model. "
            "Pale blue with a blue border is a checkpoint slice. Pale orange with an "
            "orange border is an untouched target slice. A copied target combines a "
            "checkpoint-blue fill with a target-orange border. A faded checkpoint "
            "slice with a dashed blue border is unused."
        ),
    )
    svg.rect(0, 0, LEGEND_WIDTH, LEGEND_HEIGHT, css_class="canvas", radius=18)

    add_parameter_slice(svg, x=62, y=22, state="neutral")
    svg.text(80, 40, "[C]", css_class="cell-text", anchor="middle")
    svg.text(120, 30, "ONE SQUARE = ONE PARAMETER SLICE", css_class="legend-title")
    svg.text(
        120,
        53,
        "all values move together (gray indicates no specific model)",
        css_class="legend-note",
    )

    legend_items = (
        (105, "source", "CHECKPOINT"),
        (330, "init", "TARGET"),
        (550, "unused", "UNUSED"),
        (770, "copied", "COPIED"),
    )
    for x, state, label in legend_items:
        add_parameter_slice(svg, x=x, y=91, state=state)
        svg.text(x + CELL_SIZE + 10, 109, label, css_class="legend")
    return svg.render()


def add_prefix_arrow(svg: Svg, *, x1: float, x2: float, y: float) -> None:
    svg.text((x1 + x2) / 2, y - 18, "PREFIX", css_class="prefix-label", anchor="middle")
    svg.path(
        f"M {x1} {y} L {x2} {y}",
        css_class="copy-line",
        width=3,
        marker="arrow-copy",
    )


def overlap_center(y: float, source_count: int, target_count: int) -> float:
    """Return the center of the shared, top-aligned prefix."""
    return y + grid_height(min(source_count, target_count)) / 2


def make_prefix_case_diagram(
    *,
    title: str,
    description: str,
    source_org: list[str],
    target_org: list[str],
    source_grid: list[list[str]],
    target_grid: list[list[str]],
) -> str:
    svg = Svg(
        width=STANDARD_WIDTH,
        height=STANDARD_HEIGHT,
        title=title,
        description=description,
    )
    add_standard_frame(svg)

    add_org_column(
        svg,
        card_x=SOURCE_CARD_X,
        x=ORG_SOURCE_X,
        y=ORG_Y,
        states=source_org,
        side="left",
    )
    add_org_column(
        svg,
        card_x=TARGET_CARD_X,
        x=ORG_TARGET_X,
        y=ORG_Y,
        states=target_org,
        side="right",
    )
    add_prefix_arrow(
        svg,
        x1=ORG_SOURCE_X + CELL_SIZE + 16,
        x2=ORG_TARGET_X - 16,
        y=overlap_center(ORG_Y, len(source_org), len(target_org)),
    )

    source_columns = len(source_grid[0])
    target_columns = len(target_grid[0])
    source_x = centered_grid_x(SOURCE_CARD_X, source_columns, "left")
    target_x = centered_grid_x(TARGET_CARD_X, target_columns, "right")
    add_grid(
        svg,
        card_x=SOURCE_CARD_X,
        x=source_x,
        y=GRID_Y,
        rows=len(source_grid),
        columns=source_columns,
        states=source_grid,
        side="left",
    )
    add_grid(
        svg,
        card_x=TARGET_CARD_X,
        x=target_x,
        y=GRID_Y,
        rows=len(target_grid),
        columns=target_columns,
        states=target_grid,
        side="right",
    )
    add_prefix_arrow(
        svg,
        x1=source_x + grid_width(source_columns) + 16,
        x2=target_x - 16,
        y=overlap_center(GRID_Y, len(source_grid), len(target_grid)),
    )
    return svg.render()


def make_prefix_loading_diagram() -> str:
    copied_organisms = min(EXAMPLE_CHECKPOINT_ORGANISMS, EXAMPLE_TARGET_ORGANISMS)
    copied_tracks = min(EXAMPLE_CHECKPOINT_TRACKS, EXAMPLE_TARGET_TRACKS)
    return make_prefix_case_diagram(
        title="Prefix loading with independently sized axes",
        description=(
            "The checkpoint has fewer organisms but more prediction-track/output "
            "indices than the target. The overlapping organism-by-output prefix "
            "copies. The additional target organism stays initialized, and the "
            "additional checkpoint output is unused."
        ),
        source_org=["source"] * EXAMPLE_CHECKPOINT_ORGANISMS,
        target_org=["copied"] * copied_organisms
        + ["init"] * (EXAMPLE_TARGET_ORGANISMS - copied_organisms),
        source_grid=[
            ["source"] * copied_tracks
            + ["unused"] * (EXAMPLE_CHECKPOINT_TRACKS - copied_tracks)
            for _ in range(EXAMPLE_CHECKPOINT_ORGANISMS)
        ],
        target_grid=[["copied"] * EXAMPLE_TARGET_TRACKS for _ in range(copied_organisms)]
        + [
            ["init"] * EXAMPLE_TARGET_TRACKS
            for _ in range(EXAMPLE_TARGET_ORGANISMS - copied_organisms)
        ],
    )


def make_skip_diagram() -> str:
    svg = Svg(
        width=STANDARD_WIDTH,
        height=STANDARD_HEIGHT,
        title="Skipped organism and head checkpoint loading",
        description=(
            "Checkpoint organism and head squares are unused, while every corresponding "
            "target square retains its initialization."
        ),
    )
    add_standard_frame(svg)

    add_org_column(
        svg,
        card_x=SOURCE_CARD_X,
        x=ORG_SOURCE_X,
        y=ORG_Y,
        states=["unused"] * EXAMPLE_CHECKPOINT_ORGANISMS,
        side="left",
    )
    add_org_column(
        svg,
        card_x=TARGET_CARD_X,
        x=ORG_TARGET_X,
        y=ORG_Y,
        states=["init"] * EXAMPLE_TARGET_ORGANISMS,
        side="right",
    )
    add_gate(
        svg,
        y=overlap_center(
            ORG_Y,
            EXAMPLE_CHECKPOINT_ORGANISMS,
            EXAMPLE_TARGET_ORGANISMS,
        ),
    )

    source_states = [
        ["unused"] * EXAMPLE_CHECKPOINT_TRACKS
        for _ in range(EXAMPLE_CHECKPOINT_ORGANISMS)
    ]
    target_states = [
        ["init"] * EXAMPLE_TARGET_TRACKS
        for _ in range(EXAMPLE_TARGET_ORGANISMS)
    ]
    source_x = centered_grid_x(SOURCE_CARD_X, EXAMPLE_CHECKPOINT_TRACKS, "left")
    target_x = centered_grid_x(TARGET_CARD_X, EXAMPLE_TARGET_TRACKS, "right")
    add_grid(
        svg,
        card_x=SOURCE_CARD_X,
        x=source_x,
        y=GRID_Y,
        rows=EXAMPLE_CHECKPOINT_ORGANISMS,
        columns=EXAMPLE_CHECKPOINT_TRACKS,
        states=source_states,
        side="left",
    )
    add_grid(
        svg,
        card_x=TARGET_CARD_X,
        x=target_x,
        y=GRID_Y,
        rows=EXAMPLE_TARGET_ORGANISMS,
        columns=EXAMPLE_TARGET_TRACKS,
        states=target_states,
        side="right",
    )
    add_gate(
        svg,
        y=overlap_center(
            GRID_Y,
            EXAMPLE_CHECKPOINT_ORGANISMS,
            EXAMPLE_TARGET_ORGANISMS,
        ),
        left=source_x + grid_width(EXAMPLE_CHECKPOINT_TRACKS) + 10,
        right=target_x - 10,
    )
    return svg.render()


def add_mapping_index(
    svg: Svg,
    *,
    x: float,
    y: float,
    value: str,
    role: str,
) -> None:
    svg.text(
        x,
        y + 0.5,
        value,
        css_class=f"mapping-index-text mapping-{role}-text",
        anchor="middle",
    )


def add_mapping_contents(
    svg: Svg,
    *,
    x: float,
    y: float,
    label: str,
    source: str,
    target: str,
) -> None:
    add_badge(svg, x + 17, y, label)
    add_mapping_index(svg, x=x + 53, y=y, value=source, role="source")
    svg.text(x + 82, y + 0.5, "→", css_class="mapping-arrow", anchor="middle")
    add_mapping_index(svg, x=x + 112, y=y, value=target, role="target")


def add_mapping_row(
    svg: Svg,
    *,
    y: float,
    label: str,
    source: str,
    target: str,
) -> None:
    svg.rect(
        MAPPING_CHIP_X,
        y - MAPPING_CHIP_HEIGHT / 2,
        MAPPING_CHIP_WIDTH,
        MAPPING_CHIP_HEIGHT,
        css_class="mapping-chip",
        radius=MAPPING_CHIP_HEIGHT / 2,
        extra=' stroke-width="1.75"',
    )
    add_mapping_contents(
        svg,
        x=MAPPING_CHIP_X,
        y=y,
        label=label,
        source=source,
        target=target,
    )


def add_mapping_chip(
    svg: Svg,
    *,
    y: float,
    label: str,
    source: tuple[int, int],
    target: tuple[int, int],
) -> None:
    add_mapping_row(
        svg,
        y=y,
        label=label,
        source=f"({source[0]},{source[1]})",
        target=f"({target[0]},{target[1]})",
    )


def add_organism_mapping_chip(
    svg: Svg,
    *,
    y: float,
    label: str,
    source: int,
    target: int,
) -> None:
    add_mapping_row(
        svg,
        y=y,
        label=label,
        source=str(source),
        target=str(target),
    )


def make_explicit_diagram() -> str:
    svg = Svg(
        width=STANDARD_WIDTH,
        height=STANDARD_HEIGHT,
        title="Explicit checkpoint index mapping",
        description=(
            "As in the other loading figures, the checkpoint has two organisms and "
            "four tracks while the target has three organisms and three tracks. "
            "Lettered coordinate chips pair selected source and target indices. Each "
            "flat square is one parameter slice. Unmapped target squares retain "
            "initialization."
        ),
    )
    add_standard_frame(svg)

    add_org_column(
        svg,
        card_x=SOURCE_CARD_X,
        x=ORG_SOURCE_X,
        y=ORG_Y,
        states=["source"] * EXAMPLE_CHECKPOINT_ORGANISMS,
        side="left",
        badges={0: "a", 1: "b"},
    )
    add_org_column(
        svg,
        card_x=TARGET_CARD_X,
        x=ORG_TARGET_X,
        y=ORG_Y,
        states=["copied", "init", "copied"],
        side="right",
        badges={0: "b", 2: "a"},
    )
    add_organism_mapping_chip(
        svg,
        y=org_center(ORG_Y, 0),
        label="a",
        source=0,
        target=2,
    )
    add_organism_mapping_chip(
        svg,
        y=org_center(ORG_Y, 1),
        label="b",
        source=1,
        target=0,
    )

    source_badges = {
        (0, 3): "c",
        (0, 1): "d",
        (1, 0): "e",
    }
    target_badges = {
        (2, 0): "c",
        (1, 2): "d",
        (0, 1): "e",
    }
    source_states = [
        [
            "source" if (row, column) in source_badges else "unused"
            for column in range(EXAMPLE_CHECKPOINT_TRACKS)
        ]
        for row in range(EXAMPLE_CHECKPOINT_ORGANISMS)
    ]
    target_states = [
        [
            "copied" if (row, column) in target_badges else "init"
            for column in range(EXAMPLE_TARGET_TRACKS)
        ]
        for row in range(EXAMPLE_TARGET_ORGANISMS)
    ]
    add_grid(
        svg,
        card_x=SOURCE_CARD_X,
        x=centered_grid_x(SOURCE_CARD_X, EXAMPLE_CHECKPOINT_TRACKS, "left"),
        y=GRID_Y,
        rows=EXAMPLE_CHECKPOINT_ORGANISMS,
        columns=EXAMPLE_CHECKPOINT_TRACKS,
        states=source_states,
        badges=source_badges,
        side="left",
    )
    add_grid(
        svg,
        card_x=TARGET_CARD_X,
        x=centered_grid_x(TARGET_CARD_X, EXAMPLE_TARGET_TRACKS, "right"),
        y=GRID_Y,
        rows=EXAMPLE_TARGET_ORGANISMS,
        columns=EXAMPLE_TARGET_TRACKS,
        states=target_states,
        badges=target_badges,
        side="right",
    )

    add_mapping_chip(
        svg,
        y=HEAD_MAPPING_CENTER_Y - CELL_PITCH,
        label="c",
        source=(0, 3),
        target=(2, 0),
    )
    add_mapping_chip(
        svg,
        y=HEAD_MAPPING_CENTER_Y,
        label="d",
        source=(0, 1),
        target=(1, 2),
    )
    add_mapping_chip(
        svg,
        y=HEAD_MAPPING_CENTER_Y + CELL_PITCH,
        label="e",
        source=(1, 0),
        target=(0, 1),
    )
    return svg.render()


def generated_outputs() -> dict[str, str]:
    return {
        "checkpoint-loading-legend.svg": make_legend_diagram(),
        "prefix-loading.svg": make_prefix_loading_diagram(),
        "skipped-loading.svg": make_skip_diagram(),
        "explicit-mapping.svg": make_explicit_diagram(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit unsuccessfully if committed diagrams differ from generated output",
    )
    args = parser.parse_args()

    outputs = generated_outputs()
    if args.check:
        stale = [
            name
            for name, content in outputs.items()
            if not (OUTPUT_DIR / name).is_file()
            or (OUTPUT_DIR / name).read_text(encoding="utf-8") != content
        ]
        if stale:
            print("Stale checkpoint diagrams: " + ", ".join(stale))
            return 1
        print("Checkpoint diagrams are up to date.")
        return 0

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, content in outputs.items():
        path = OUTPUT_DIR / name
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")
            print(f"Wrote {path.relative_to(DOCS_DIR.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
